-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Books.Object.Book exposing (author, title)

import Books.InputObject
import Books.Interface
import Books.Object
import Books.Scalar
import Books.ScalarDecoders
import Books.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
title : SelectionSet String Books.Object.Book
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| -}
author : SelectionSet String Books.Object.Book
author =
    Object.selectionForField "String" "author" [] Decode.string
